title: The American Legal Lexicon

remote_theme: just-the-docs/just-the-docs


# Navigation Menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
    children:
      - title: "Project 1"
        url: "/projects/project1/"
      - title: "Project 2"
        url: "/projects/project2/"

# Plugins
plugins:
  - jekyll-remote-theme

# Collections (optional, not needed unless you're using special layout logic)
# You could omit this unless you want to loop over `projects` somewhere
# collections:
#   projects:
#     output: true
#     permalink: /pages/projects/:path/
