title: The American Legal Lexicon

remote_theme: just-the-docs/just-the-docs

# Custom CSS (optional)
just_the_docs:
  custom_css:
    - /assets/css/custom.css

# GitHub Pages configuration
baseurl: "" # Leave empty if publishing from root (e.g., username.github.io or using /docs)
url: "https://<your-username>.github.io/<repo-name>" # Replace with actual username/repo

# Navigation Menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/pages/projects/"
    children:
      - title: "Project 1"
        url: "/pages/projects/project1/"
      - title: "Project 2"
        url: "/pages/projects/project2/"

# Plugins
plugins:
  - jekyll-remote-theme

# Collections (optional, not needed unless you're using special layout logic)
# You could omit this unless you want to loop over `projects` somewhere
# collections:
#   projects:
#     output: true
#     permalink: /pages/projects/:path/

# Defaults
defaults:
  - scope:
      path: "pages/projects"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown processor
markdown: kramdown
