title: The American Legal Lexicon
remote_theme: just-the-docs/just-the-docs

logo: "/assets/images/ALL_Logo.png"
color_scheme: dark


nav_enabled: true


nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
    children:
      - title: "Projects Overview"
        url: "/projects/"
      - title: "Project 1"
        url: "/projects/project1"
      - title: "Project 2"
        url: "/projects/project2"
  - title: "Teaching"
    children:
      - title: "Syllabus"
        url: "/teaching/syllabus"
      - title: "Assignments"
        url: "/teaching/assignments"

plugins:
  - jekyll-remote-theme

