# _config.yml for Jekyll site with just_the_docs theme

title: My Jekyll Site
description: A sample Jekyll site with just_the_docs theme
#url: "https://your-github-username.github.io"  # Set your GitHub Pages URL
#baseurl: ""  # Root URL
#repository: "https://github.com/your-github-username/your-repository"

# Theme settings
remote_theme: just-the-docs

# Navigation settings
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects

# Enable or disable the search feature (true/false)
search_enabled: true

# Enable or disable the table of contents for each page (true/false)
toc_enabled: true

# Path for custom assets (like images, CSS, JavaScript)
assets:
  - assets/stylesheets
  - assets/images
  - assets/css

# Markdown processor (default: kramdown)
markdown: kramdown

# Permalink structure (adjust as needed)
permalink: pretty


# Build settings
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Add any custom configurations you may need
plugins:
  - jekyll-feed
  - jekyll-seo-tag
